### PR TITLE
Changed to CheckboxListTile

### PR DESCRIPTION
**Pull request by oei8ht**

### CODE REVIEW

**Comment by rrousselGit** [comment]
Why such change?

This removes all the edit logic.

**Comment by oei8ht** [comment]
> Why such change?
> 
> This removes all the edit logic.

I'm of the opinion that when people make to-dos, they are unlikely to want to change the content. Also, if the edit logic is of importance, it can still be implemented as a longpress using GestureDetector or otherwise. It seems like a more realistic use-case scenario.

**Comment by rrousselGit** [comment]
I disagree.
This showcase both how to handle edits with Riverpod and how hooks can handle focus.

**Comment by rrousselGit** [comment]
Could you update the tests then? And generate a golden file for the strike-through

**Comment by rrousselGit** [comment]
Closing as I don't think this change adds meaningful improvements on "how Riverpod works" and only demonstrates how to use Flutter.

**Pull request closed without merging**
