### PR TITLE
Add Weather app example for website

### PR DESCRIPTION
**Pull request by campanagerald**
Add new example, this is a forked from [ResoCoder's Weather Bloc](https://github.com/ResoCoder/flutter-bloc-library-v1-tutorial) tutorial which I converted to Riverpod.

[https://github.com/campanagerald/flutter-bloc-library-v1-tutorial](https://github.com/campanagerald/flutter-bloc-library-v1-tutorial)

### CODE REVIEW

**Comment by campanagerald** [comment]
Hi @rrousselGit, 

Sorry I don't know why codecov was not successful. I have only changed one file.

**Comment by rrousselGit** [comment]
Don't worry about it, thanks!

**Comment by iamarnas** [comment]
@campanagerald Hi! I just want to ask. I wonder why you choose handle state in the StateNotifier with your own state. With AsyncValue could not be easer and cleaner? I like to hear others developers opinions.

**Comment by campanagerald** [comment]
> @campanagerald Hi! I just want to ask. I wonder why you choose handle state in the StateNotifier with your own state. With AsyncValue could not be easer and cleaner? I like to hear others developers opinions.

Hi @iamarnas. I am used to flutter_bloc. I chose to handle my own state with StateNotifier because I want to replicate what flutter_bloc can do using river_pod. You are correct, its much simpler when I use AsyncValue. You have many options with river_pod though.

**Comment by iamarnas** [comment]
@campanagerald Personally I like more how flutter_bloc represent state handling it's more describe what you do and easier understand. But with Riverpod I found `AsyncValue` which do same thing with few lines 😊

**Comment by campanagerald** [comment]
@iamarnas you are right. 😊  I am just playing with river_pod, maybe I should try to use AsyncValue.

**Pull request merged**
