### PR TITLE
add Japanese docs for website

### PR DESCRIPTION
**Pull request by toshi-kuji**
This PR will add Japanese translations of the .mdx files for the website, plus add ja-locale to **website/docusaurus.config.js**.

All recent changes/additions made to the English version of the documents are reflected.

[additional note]
I've also made some changes on Japanese wordings on **code.json** and **current.json** from the last PR #1021

### CODE REVIEW

**Comment by rrousselGit** [comment]
That's epic, thank you!

**Comment by rrousselGit** [comment]
It looks like deploy is failing because the Dart snippets imports are incorrect. Could you fix that? :pray:

**Comment by rrousselGit** [comment]
> On a side note, I did not translate the [refresh.mdx] and [search_as_we_type.mdx] yet, since they seem to be not public yet.



That's fair, I'm not done with those anyway :)

**Comment by toshi-kuji** [comment]
@rrousselGit done!

**Comment by rrousselGit** [comment]
Awesome thanks!

**Pull request merged**
