### PR TITLE
Added StatusNotifier example

### PR DESCRIPTION
**Pull request by omensight**
I have created a example of StateNotifier

### CODE REVIEW

**Comment by rrousselGit** [comment]
Thanks!

Could you explain what you think this example brings over others? I would expect the counter example to have the same "use-case"

**Comment by omensight** [comment]
> Thanks!
> 
> Could you explain what you think this example brings over others? I would expect the counter example to have the same "use-case"

I created this example because I didn't find a way to access the state notifier in the latest 1.0 dev version.

So do you mean this example should be about the already existing counter example?

Thanks for reply.

**Comment by rrousselGit** [comment]
I see.

What you do think about refactoring the counter to use StateNotifierProvider instead of StateProvider?

**Comment by omensight** [comment]
Let me correct this.

**Pull request merged**
