### PR TITLE
Italian complete docs translation

### PR DESCRIPTION
**Pull request by marcoredz**
## What's changed?
Added all the missing part of the Italian docs translation, including comments in the code snippets.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Hello!

It seems import links are broken (see CI logs). Could you fix those? :pray:

**Comment by marcoredz** [comment]
Yes, I just saw. 
Proceeding

**Comment by marcoredz** [comment]
@rrousselGit is it ok now?

**Comment by rrousselGit** [comment]
It's looking good, thanks a lot!

**Pull request merged**
