### PR TITLE
Added documentation for ProviderObserver

### LINKED ISSUE #132: Document ProviderObserver / How to do Logging with Riverpod
Related to https://github.com/rrousselGit/river_pod/issues/131

### PR DESCRIPTION
**Pull request by yiss**
Close #132

### CODE REVIEW

**Comment by yiss** [comment]
@rrousselGit Let me know what do you think. Also I noticed that when a value of provider is logged it show Instance of 'StateController<int>' maybe should add toString() method to StateController to expose the value instead ?

**Comment by rrousselGit** [comment]
Thanks a lot!

A few things:
- I don't think we need to remind users what a provider or Consumer is.
- We should list all the life-cycles of this object (so `didAddProvider` & co)
- I like to start these pages with a description of "A use-case for this class" – typically logging & devtools

**Comment by yiss** [comment]
@rrousselGit I'll make those changes. When you say that we don't need to remind users of what a consumer or provider is you mean in the example ?

**Comment by rrousselGit** [comment]
Yes. I was referring to the comments, which explains what Consumer/context.read are

**Comment by yiss** [comment]
@rrousselGit I think it's good now let me know if it needs any changes :)

**Comment by rrousselGit** [comment]
Thanks!

**Pull request merged**
