### PR TITLE
[Update] The Korean documentation on the Getting Started Page.

### PR DESCRIPTION
**Pull request by JAICHANGPARK**
## Commit 
- [Add] add getting started korean translate

## What's changed?
1. [Update] Update Document about  Korean translate 
2. [Update] Update getting start document page 
3. [Update] Changed the language more naturally (Korean)

## Compare

| Before |  after  |
|---|---|
| image  |   image |
|image |image|

### CODE REVIEW

**Comment by JAICHANGPARK** [comment]
I will continue to translate when I have time.

**Comment by JAICHANGPARK** [comment]
bf777f5  [Fix] Fixed the cause of failure in github build.

**Comment by rrousselGit** [comment]
@JAICHANGPARK Why did you close this? 🤔

**Comment by JAICHANGPARK** [comment]
@rrousselGit 

I PR with some more Korean translations added.

#1189 

Thanks

**Pull request closed without merging**
