### PR TITLE
Allow refreshing provider of nullable value

### PR DESCRIPTION
**Pull request by AlexHartford**
Fixes https://github.com/rrousselGit/river_pod/issues/445

### CODE REVIEW

**Comment by rrousselGit** [comment]
Nice thanks!

Do you mind writing a test for it?

**Comment by AlexHartford** [comment]
> Nice thanks!
> 
> Do you mind writing a test for it?

Started writing the test but then realized I couldn't reproduce the error using the original code.

**Review by derolf — APPROVED** [review]

**Review by derolf — APPROVED** [review]
Looks good!

**Comment by AlexHartford** [comment]
@rrousselGit I just added a test, let me know if it looks good!

**Review by rrousselGit — APPROVED** [review]
LGTM

will merge and publish later today

**Pull request merged**
