### PR TITLE
Improve documentation

### PR DESCRIPTION
**Pull request by TimWhiting**
Hi Remi,

This is still a work in progress, and I haven't addressed some of the issues with documentation directly. 

What's new:
- Section on provider lifecycles
- Section on Immutability
- Section on scoping
- Placeholder section on different provider types and their differences (not finished, and likely to change with the RFCs)
- Added dark / light versions of the imports decision digram
- Moved intro video to a history directory - I'm not sure if the video is that helpful anymore, since Riverpod has changed much since it was recorded, but I'm thinking that a history section might be useful for migration guides.

Small grammar fixes in other files.

Rearranged the testing guide to be below the concepts section. (You need to understand the concepts before moving on to testing).

Still todo:
- [ ] More information on dealing with asynchronous initialization
- [ ] More information on dealing with asynchronous values / dependencies from within a `StateNotifier`
- [ ] Make sure that when a provider is disposed is clear, especially for autoDispose, and understanding how to make sure objects aren't disposed before they should be
- [ ] Clean up loose ends

### CODE REVIEW

**Comment by rrousselGit** [comment]
Awesome!

I'll take a look later today 😊

**Comment by rrousselGit** [comment]
:wave:

Do you still plan on working on this? :smile:

**Comment by TimWhiting** [comment]
Yes, I've been a bit busy recently. But I do plan on continue working on it soon. I'd like some feedback to see if this is going in a good direction, and also want to know your preference on when to use code blocks versus links for highlighting terms / class names / class methods etc.

**Comment by rrousselGit** [comment]
No worries, take your time.

Although it's worth noting that I do plan on re-architecturing the documentation too (not just adding new things).
I'd like to change the flow for newcomers, to provide a smoother path from zero to some basic understanding.

Maybe it'd be worth having a chat privately to discuss about this?

**Comment by TimWhiting** [comment]
Yeah, a private chat sounds good. I think a new flow for newcomers sounds like an excellent idea.

**Comment by aspiiire** [comment]
> I've tried to keep it mergeable with master, but I haven't had the time I'd like to dedicate to this to make it what I think it deserves. You are welcome to help out if you want. There are quite a few changes in v1.0 that probably still need to be addressed in the documentation. The CHANGELOG is probably best for understanding what needs to be updated or added.
> 
> Thanks for the offer to help!

Can I help with something? Where I find the changelog? I want to ask another thing, I was planning to create the italian version of the docs for the old version, but this means that I should wait for this one to finish and then translate, am I right?

**Comment by rrousselGit** [comment]
>  I want to ask another thing, I was planning to create the italian version of the docs for the old version, but this means that I should wait for this one to finish and then translate, am I right?



No need to wait for this PR to land. While there are some docs updates planned, it mostly involve new docs and changing the sidebar.

**Comment by rrousselGit** [comment]
@TimWhiting In your opinion, are there any bits in there that would be worth extracting and merging into the current doc right now?

**Comment by TimWhiting** [comment]
> @TimWhiting In your opinion, are there any bits in there that would be worth extracting and merging into the current doc right now?

Yes, I will extract the parts out that I feel are ready to merge, and then I will try to merge new sections in as they are ready.

**Pull request closed without merging**
