### PR TITLE
add German translation

### PR DESCRIPTION
**Pull request by devcat-net**
Added the german translation to the mdx files and also to the comments of the dart files

### CODE REVIEW

**Comment by rrousselGit** [comment]
Thanks!

It seems like you misunderstood how translations works though. You shouldn't modify English files
Instead you should make a folder within the i18n folder that contains German equivalent

The changes you made here basically removes English

**Comment by devcat-net** [comment]
Sorry, my mistake.

I will put the mdx files in a de subfolder of i18n. Where should I put the code snippets with the translated comments?

**Comment by rrousselGit** [comment]
They should be next to the german mdx files

**Comment by devcat-net** [comment]
The translations are under the i18n folder in the de subfolder in the latest commit.

**Comment by rrousselGit** [comment]
Awesome work, thanks a lot!

**Pull request merged**
